name: flutter_bloc_extensions
description: Collection of helper objects extending flutter_bloc library.
version: 0.1.2
author: Ondřej Kunc <kunc.ondrej1@gmail.com>
homepage: https://github.com/OndrejKunc/flutter_bloc_extensions

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any
  flutter_bloc: ^0.13.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_bloc:
    git:
      url: https://github.com/OriontheCat/bloc
      path: packages/flutter_bloc